---
title: "eda"
author: "Team Infinite Limits"
date: "October 29, 2017"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(rpart)
library(DMwR2)
library(randomForest)
library(rpart.plot)
library(leaps)
source("label_data.R")
knitr::opts_chunk$set(echo = TRUE)

set.seed(123)
train_sample<-sample.int(nrow(health),size=round(.6*nrow(health)))
inds=1:nrow(health)

health_test<-health[inds[-train_sample],]
#health<-health[inds[train_sample],]

```

```{r echo=TRUE}

health %>%
  ggplot(aes(x=FAMRACEW1)) +
  geom_bar(aes(group=1,y=..prop..)) +
  coord_flip()

```


```{r echo=TRUE}

health %>%
  ggplot(aes(x=CGRADEW1)) +
  geom_bar()

```

```{r echo=TRUE}
health %>%
  filter(!is.na(CSEXW1)) %>%
  ggplot() +
  geom_density(aes(x=CGPATOTW1),na.rm=TRUE) +
  facet_wrap(~CSEXW1,drop=TRUE)
```


```{r echo=FALSE}
set.seed(123)
rh <- health %>%
  select(-CGPASTEMW1,-BIRTHYR) %>%
  filter(!is.na(CGPATOTW1))

rf_model<-rpartXse(CGPATOTW1 ~ ., data=rh)

prp(rf_model)
```

```{r echo=TRUE}
health %>%
  mutate_all(is.na) %>%
  summarise_all(sum) %>%
  gather(key="varname",value="sumnas") %>%
  arrange(desc(sumnas))
```

```{r echo=TRUE}
rhs <- health %>%
  select(
  DLYACT1W1,
  PHYSXMW1,
  DENTXMW1,
  BARMEDCR,
  H1GH53,
  RELIGIONW1,
  IMPRELW1,
  YRSSCHLW1,
  TWINW1,
  TWNSMHSW1,
  BIOPLVWT,
  CLUBACADW1,
  CLUBMUARTW1,
  CLUBSPORTW1,
  CRPWBW1,
  CSCLBELNGW1,
  SOCSPPTW1,
  POSFMENVW1,
  CATONMYW1,
  COLEXPW1,
  NGHSOCCAPW1,
  MWARMTHW1,
  DWARMTHW1,
  MPOSRELW1,
  CGPATOTW1
  )
set.seed(927)
tree_mod <- rpartXse(CRPWBW1 ~ ., rhs)
prp(tree_mod)
```

```{r echo=TRUE}
rhs_dropped <- na.omit(rhs)
rhs_dropped <- rhs %>%
  mutate_if(is.factor,droplevels) %>%
  select_if(function(x) length(unique(x))>1)

mod <- lm (CGPATOTW1 ~ SOCSPPTW1, data=rhs_dropped, na.action=na.omit)
```


```{r echo=TRUE}
health %>%
  ggplot(aes(x=health$DEPREW1)) +
  geom_density() +
  geom_point(x=health$DEPREW1,y=0)
  
```
```{r echo=TRUE}

health %>%
  filter(!is.na(DEPREW1) & DEPREW1 > 0) %>%
  mutate(DEPREW1=log(DEPREW1)) %>%
  ggplot(aes(x=DEPREW1)) +
  geom_histogram(binwidth = .15) +
  geom_point(aes(x=DEPREW1,y=0))

```
```{r echo=TRUE}
qqnorm(log(health$DEPREW1[health$DEPREW1>0]))#+runif(length(health$DEPREW1[health$DEPREW1>0]),min=-.03,max=.03))
```

Depression in students

```{r echo=TRUE}
health %>%
  filter(!is.na(DEPREW1) & DEPREW1 > 0) %>%
  mutate(DEPREW1=log(DEPREW1)) %>%
  ggplot(aes(x=DEPREW1)) +
  geom_density() +
  facet_wrap(~SCHSUSPEN)
```
```{r echo=TRUE}
health %>%
  filter(!is.na(DEPREW1) & DEPREW1 > 0) %>%
  mutate(DEPREW1=log(DEPREW1)) %>%
  ggplot() +
  geom_point(aes(x=H1GH45,y=DEPREW1))
```
```{r echo=TRUE}

health %>%
  select(DLYACT1W1,DLYACT2W1,DLYACT3W1,DLYACT4W1,DLYACT5W1,DLYACT6W1,DLYACT7W1) %>%
  mutate_all(as.numeric) %>%
  cor(use="complete.obs")
```


```{r echo=TRUE}


predictors <- unique(c("INTELLW1" , "MFUTEXPW1" , "DFUTEXPW1", "CGPATOTW1",
                  "NEGLFEXPW1", "POSLFEXPW1" , "SELFESTW1" , "MENTHFREW1" , "WLUNHLTHW1" ,
                  "BODYIMGW1" , "MOMEDW1" , "MOMWKW1" , "DADWKW1" , 
                  "IMPRELW1" , "SOCSPPTW1" , "H1GH48", "ADOPTW1",
                  "POSFMENVW1", "BIO_SEX", "SLEEP","SCLBELNG2W1","SCHLTRBLW1","CPRBEHLMW1",
                  "SCHEXPEL","PHYHFREQW1","CRPWBW1","CSCLBELNGW1",
                  "DLYACT1W1","DLYACT2W1","DLYACT3W1","DLYACT4W1","DLYACT5W1","DLYACT6W1","DLYACT7W1",
                  "CLUBACADW1","CLUBMUARTW1","CLUBSPORTW1","BIRTHYR"))


health_rmna <- na.omit(health[,c("DEPREW1",predictors)])
health_rmna <-droplevels.data.frame(health_rmna)
health_rmna <- health_rmna %>%
  mutate_at(vars(INTELLW1,BODYIMGW1,IMPRELW1,H1GH48,starts_with("DLYACT"),starts_with("CLUB")), as.numeric)
health_rmna <- health_rmna %>%
  filter(DEPREW1 > 0) %>%
  mutate(DEPREW1 = log(DEPREW1))

```

```{r echo=TRUE}

health_rmna <- health_rmna[c(-337,-382,-172,-916),]

form<-as.formula(paste("DEPREW1 ~ ", paste(predictors,collapse="+")))

depmod <- lm(form,data=health_rmna, na.action=na.omit)

depmod_both<-step(depmod,direction="both",trace=0)

summary(depmod_both)
```

Verify that the daily activity variables are not colinear

```{r echo=TRUE}
pc<-health_rmna %>%
  select_at(vars("DLYACT1W1","DLYACT2W1","DLYACT3W1","DLYACT4W1","DLYACT5W1","DLYACT6W1","DLYACT7W1")) %>%
  cor()
pc
```

Verify that the club activities are not colinear


```{r echo=TRUE}
pc<-health_rmna %>%
  select_at(vars(starts_with("CLUB"))) %>%
  cor()
pc
```

```{r echo=TRUE}
leaps <- regsubsets(depmod_both$call$formula, data=health_rmna, really.big=TRUE, nvmax=6)
plot(leaps,scale="adjr")
```

```{r message=FALSE, warning=FALSE, include=FALSE}

multiplot <- function(..., plotlist=NULL, cols) {
    require(grid)

    # Make a list from the ... arguments and plotlist
    plots <- c(list(...), plotlist)

    numPlots = length(plots)

    # Make the panel
    plotCols = cols                          # Number of columns of plots
    plotRows = ceiling(numPlots/plotCols) # Number of rows needed, calculated from # of cols

    # Set up the page
    grid.newpage()
    pushViewport(viewport(layout = grid.layout(plotRows, plotCols)))
    vplayout <- function(x, y)
        viewport(layout.pos.row = x, layout.pos.col = y)

    # Make each plot, in the correct location
    for (i in 1:numPlots) {
        curRow = ceiling(i/plotCols)
        curCol = (i-1) %% plotCols + 1
        print(plots[[i]], vp = vplayout(curRow, curCol ))
    }

}

graphs = list()

for(i in 1:length(names(intel_mod2$model))) {
  var_name=names(depmod_both$model)[i]
  temp <- as.tibble(cbind(X=depmod_both$model[[var_name]],Y=depmod_both$residuals))
  g <- ggplot(data=temp) +
    geom_point(aes(x=X,y=Y)) 
  graphs[[i]]<-g
}


```

```{r echo=TRUE}

as.tibble(cbind(CGPATOTW1=depmod_both$model$CGPATOTW1,residuals=depmod_both$residuals)) %>%
  ggplot() + 
  geom_point(aes(x=CGPATOTW1,y=residuals))

```
```{r echo=TRUE}
as.tibble(cbind(NEGLFEXPW1=depmod_both$model$NEGLFEXPW1,residuals=depmod_both$residuals)) %>%
  ggplot() + 
  geom_point(aes(x=NEGLFEXPW1,y=residuals))
```
```{r echo=TRUE}
as.tibble(cbind(SELFESTW1=depmod_both$model$SELFESTW1,residuals=depmod_both$residuals)) %>%
  ggplot() + 
  geom_point(aes(x=SELFESTW1,y=residuals))
```
```{r echo=TRUE}
as.tibble(cbind(MENTHFREW1=depmod_both$model$MENTHFREW1,residuals=depmod_both$residuals)) %>%
  ggplot() + 
  geom_point(aes(x=MENTHFREW1,y=residuals))
```

```{r echo=TRUE}
as.tibble(cbind(MENTHFREW1=depmod_both$model$MENTHFREW1,residuals=depmod_both$residuals)) %>%
  ggplot() + 
  geom_point(aes(x=MENTHFREW1,y=residuals))
```

```{r echo=TRUE}
as.tibble(cbind(WLUNHLTHW1=depmod_both$model$WLUNHLTHW1,residuals=depmod_both$residuals)) %>%
  ggplot() + 
  geom_point(aes(x=WLUNHLTHW1,y=residuals))
```

```{r echo=TRUE}

set.seed(927)
rf_mod <- randomForest(form, data=health_rmna)

imp<-importance(rf_mod)
```

```{r echo=TRUE}
predictors <- unique(c("INTELLW1" , "MFUTEXPW1" , "DFUTEXPW1", "CGPATOTW1",
                  "NEGLFEXPW1", "POSLFEXPW1" , "SELFESTW1" , "MENTHFREW1" , "WLUNHLTHW1" ,
                  "BODYIMGW1" , "MOMEDW1" , "MOMWKW1" , "DADWKW1" , 
                  "IMPRELW1" ,"CLUBAVG" , "SOCSPPTW1" , "H1GH48", "ADOPTW1",
                  "POSFMENVW1", "BIO_SEX", "SLEEP","SCLBELNG2W1","SCHLTRBLW1","CPRBEHLMW1",
                  "SCHEXPEL","PHYHFREQW1","CRPWBW1","CSCLBELNGW1","DLYACT1W1",
                  "DLYACT2W1","DLYACT3W1","DLYACT4W1","DLYACT5W1","DLYACT6W1","DLYACT7W1"))

health_rmna <- na.omit(health[,c("DEPREW1",predictors)])
health_rmna <-droplevels.data.frame(health_rmna)
health_rmna <- health_rmna %>%
  filter(DEPREW1 > 0) %>%
  mutate(DEPREW1 = log(DEPREW1))
depmod.acts <- lm(as.formula(paste("DEPREW1 ~ ", paste(c(predictors,"BODYIMGW1*BIO_SEX"),collapse="+"))),
                data=health_rmna, na.action=na.omit)
depmod.acts2<-step(depmod.acts,trace=0)

anova(depmod.acts2,depmod_both)
```

```{r echo=TRUE}
leaps <- regsubsets(depmod.acts2$call$formula, data=health_rmna,really.big=TRUE)
plot(leaps, scale="adjr")
```

```{r echo=TRUE}
library(performanceEstimation)
res <- performanceEstimation(
  PredTask(depmod_both$call$formula, health_rmna, "DEPREW1"),
  c(
    Workflow(
      learner = "lm"
    ),
    workflowVariants(learner = "rpartXse", learner.pars = list(se = c(0, 0.5, 1))),
    Workflow(
      learner="randomForest"
    )
  ),
  EstimationTask(metrics = "nmse", method = CV(nReps = 5, nFolds = 10))
)
```

```{r echo=TRUE}
library(performanceEstimation)

set.seed(2)

# n_dep <- sum(health_rmna$DEPFACT=="Depressed")
# 
# health_nodep <- health_rmna %>%
#   filter(DEPFACT == "Not Depressed") %>%
#   sample_n(5*n_dep)
# 
# health_dep <- health_rmna %>%
#   filter(DEPFACT == "Depressed")
# 
# health_samp <- rbind(health_dep,health_nodep)

glm_pred <- function(obj, test, p){
  r<-ifelse(predict(obj,test,type="response")>p,"Not Depressed","Depressed")
  as.vector(factor(r))
}

da_pred <- function(obj,test) {
  predict(obj,test)$class
}


form <- as.formula(paste("DEPFACT ~ ", paste(predictors,collapse="+")))
res <- performanceEstimation(
  PredTask(form, health_rmna),
  c(
    workflowVariants(
      learner = "glm",
      learner.pars=list(family=binomial),
      predictor.pars=list(p=c(.5,.9,.95)),
      predictor="glm_pred"
    ),
    Workflow(learner = "lda",
             predictor="da_pred"),
    Workflow(learner = "naiveBayes",
             deps=list(packages=c("e1071"))),
    Workflow(
      learner="randomForest"
    )
  ),
  EstimationTask(metrics = c("prec","acc"), method = CV(nReps = 10, nFolds = 5))
)
save(res,file="workflow_class")
```
```{r echo=TRUE}
library(performanceEstimation)
res <- performanceEstimation(
  PredTask(dep.nolog.step$call$formula, health_rmna2, "DEPREW1"),
  c(
    Workflow(
      learner = "lm"
    ),
    workflowVariants(learner = "rpartXse", learner.pars = list(se = c(0, 0.5, 1))),
    Workflow(
      learner="randomForest"
    )
  ),
  EstimationTask(metrics = "nmse", method = CV(nReps = 5, nFolds = 10))
)
```